In [1]:
import numpy as np

In [2]:
A = np.array([[2, 1, 1], [-5, -3, 0], [1, 1, -1]])
A

array([[ 2,  1,  1],
       [-5, -3,  0],
       [ 1,  1, -1]])

In [3]:
b = np.array([[-1], [1], [-2]]) # Important format
b

array([[-1],
       [ 1],
       [-2]])

In [4]:
# Compute the rank of A
# it is full rank and invertable

np.linalg.matrix_rank(A)

3

In [5]:
# Find the inverse of A
Ainv = np.linalg.inv(A)
Ainv

array([[-3., -2., -3.],
       [ 5.,  3.,  5.],
       [ 2.,  1.,  1.]])

In [6]:
# Use the inverse of A to compute x

x = np.dot(Ainv, b)
x

array([[  7.],
       [-12.],
       [ -3.]])

In [7]:
# Check the solution to get back b

# x1 = 7
# x2 = -12
# x3 = -3

# Check the solution to get the b

# To test the answer

np.dot(A, x)

# to return b

array([[-1.],
       [ 1.],
       [-2.]])

In [8]:
# Solving linear equation alternatively using linalg modulr
# It provides similar results

x = np.linalg.solve(A, b)
x

array([[  7.],
       [-12.],
       [ -3.]])

In [9]:
# Updating equations 5x2 - x3 = 1

A = np.array([[2, 1, 1], [-5, -3, 0], [1, 1, -1], [0, 5, -1]])
A

array([[ 2,  1,  1],
       [-5, -3,  0],
       [ 1,  1, -1],
       [ 0,  5, -1]])

In [10]:
b = np.array([[-1], [1], [-2], [1]]) # Important 
b

array([[-1],
       [ 1],
       [-2],
       [ 1]])

In [11]:
# Compute the rank of A

np.linalg.matrix_rank(A)

3

In [ ]:
# Find the inverse of A
# It is not invertable now

# least square method is necessary to solve matrix which are not square

Ainv = np.linalg.inv(A)
Ainv