In [6]:
import numpy as np

In [1]:
x = [5, 7, -2, 2]
y = [4, 5, 12, 0]

In [2]:
x

[5, 7, -2, 2]

In [3]:
y

[4, 5, 12, 0]

Now, we could perform the multiplications using a for loop as follows:

In [4]:
product = []
for i in range(len(x)):
    product.append(x[i] * y[i])
product

[20, 35, -24, 0]

However, if we store our numbers as arrays, we can get the equivalent result with just
one line of code

In [7]:
np.array(x) * np.array(y)

array([ 20,  35, -24,   0])

A vector is essentially an ordered collection of numbers that are written in a column.

Vector and Matrics in Numpy

In [8]:
# import numpy as np

A = np.array([[1, 2], [2, 1]])

In [9]:
A

array([[1, 2],
       [2, 1]])

In [10]:
B = np.array([[1, 5], [0, 2]])

In [11]:
B

array([[1, 5],
       [0, 2]])

We can then perform addition, subtraction, and multiplication by a scalar. All of these
operations behave consistently with the rules of linear algebra. That is, they are
performed element-wise. Let’s try this out

In [12]:
A + 5 * B

array([[ 6, 27],
       [ 2, 11]])

Matrix multiplication using np.dot()

In [16]:
A * B # Element wise hadamard product, Not matrice product

array([[ 1, 10],
       [ 0,  2]])

In [17]:
np.dot(A, B) # Matrix multiplication

array([[ 1,  9],
       [ 2, 12]])

### Vectors as one-dimensional arrays
When representing vectors in NumPy, we have several choices. Perhaps the most natural
way to represent them is using a one-dimensional array. 

In [18]:
a = np.array([0, 1, 2])

In [19]:
a

array([0, 1, 2])

There is, however, a potential pitfall with this choice. In NumPy, there is no distinction
between a vector and its transpose (using the .T notation in Python), they are both the
same one-dimensional array.

In [20]:
a.T

array([0, 1, 2])