In [1]:
import numpy as np

In [1]:
x = [5, 7, -2, 2]
y = [4, 5, 12, 0]

In [2]:
x

[5, 7, -2, 2]

In [3]:
y

[4, 5, 12, 0]

Now, we could perform the multiplications using a for loop as follows:

In [4]:
product = []
for i in range(len(x)):
    product.append(x[i] * y[i])
product

[20, 35, -24, 0]

However, if we store our numbers as arrays, we can get the equivalent result with just
one line of code

In [7]:
np.array(x) * np.array(y)

array([ 20,  35, -24,   0])

A vector is essentially an ordered collection of numbers that are written in a column.

Vector and Matrics in Numpy

In [8]:
# import numpy as np

A = np.array([[1, 2], [2, 1]])

In [9]:
A

array([[1, 2],
       [2, 1]])

In [10]:
B = np.array([[1, 5], [0, 2]])

In [11]:
B

array([[1, 5],
       [0, 2]])

We can then perform addition, subtraction, and multiplication by a scalar. All of these
operations behave consistently with the rules of linear algebra. That is, they are
performed element-wise. Let’s try this out

In [12]:
A + 5 * B

array([[ 6, 27],
       [ 2, 11]])

Matrix multiplication using np.dot()

In [16]:
A * B # Element wise hadamard product, Not matrice product

array([[ 1, 10],
       [ 0,  2]])

In [17]:
np.dot(A, B) # Matrix multiplication

array([[ 1,  9],
       [ 2, 12]])

### Vectors as one-dimensional arrays
When representing vectors in NumPy, we have several choices. Perhaps the most natural
way to represent them is using a one-dimensional array. 

In [18]:
a = np.array([0, 1, 2])

In [19]:
a

array([0, 1, 2])

There is, however, a potential pitfall with this choice. In NumPy, there is no distinction
between a vector and its transpose (using the .T notation in Python), they are both the
same one-dimensional array.

In [20]:
a.T

array([0, 1, 2])

This means in particular that we can multiply together a vector by itself

In [21]:
np.dot(a, a)

5

This is actually what we would expect to get using the operation a⊤a
. Now this is not
necessarily a problem as long as we are aware of this behavior. But what if we wanted to
actually work with a⊤ a
, the actual row vector. We would then have to define as a two-
dimensional array with shape (3, 1)
as follows:

In [22]:
b = np.array([[0], [1], [2]])

In [23]:
b

array([[0],
       [1],
       [2]])

Essentially this is the same vector, but choosing to represent it using a two-dimensional
array in NumPy changes the way that operations such as the transpose and matrix
multiplication behave. In particular, the transpose is now clearly distinguished

In [24]:
b.T

array([[0, 1, 2]])

In [25]:
b.shape

(3, 1)

In [26]:
b.T.shape

(1, 3)

Note that now we can no longer multiply of multiplying a (3, 1) (3, 1)
matrix by a b
by itself because that would be the equivalent
matrix and the dimensions are not compatible:

In [ ]:
np.dot(b, b) # Error

We can, however, compute and
b⊤b bb⊤

In [28]:
np.dot(b.T, b)

array([[5]])

In [29]:
np.dot(b, b.T)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

And the results are as expected. Note in particular that both results are returned as two-
dimensional arrays.

#### NumPy broadcasting revisited
When computing operations between two-dimensional arrays in NumPy, we have a
much wider range of possibilities than in conventional linear algebra due to the
broadcasting concept that you were introduced to before. 

In [30]:
a = np.array([[0], [7]])
b = np.array([[1, 2], [0, 6]])
c = np.array([[2, 2]])

In [31]:
a

array([[0],
       [7]])

In [32]:
a.shape

(2, 1)

In [33]:
b.shape

(2, 2)

In [34]:
c.shape

(1, 2)

In [35]:
a

array([[0],
       [7]])

In [36]:
c

array([[2, 2]])

In [37]:
a+c

array([[2, 2],
       [9, 9]])

In [38]:
a*b

array([[ 0,  0],
       [ 0, 42]])

It is important to remember that broadcasting is always done element-wise!

Linalg Module

In [2]:
# import numpy as np

A = np.array([[3, 4], [2, 3]])

In [3]:
A

array([[3, 4],
       [2, 3]])

In [4]:
A.T

array([[3, 2],
       [4, 3]])